### ISSUE TITLE
Brak klasy android

### ISSUE THREAD

**Issue by mekkolodziejski** [dotpay/Mobile-SDK-Android#20]
Po wybraniu płatności wywala aplikację. 
java.lang.ClassNotFoundException: Didn't find class "com.visa.checkout.CheckoutButton"

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.smartcode.myapplication, PID: 32059
    android.view.InflateException: Binary XML file line #90 in com.smartcode.myapplication:layout/dpsdk_fragment_user_data: Binary XML file line #90 in com.smartcode.myapplication:layout/dpsdk_fragment_user_data: Error inflating class com.visa.checkout.CheckoutButton
    Caused by: android.view.InflateException: Binary XML file line #90 in com.smartcode.myapplication:layout/dpsdk_fragment_user_data: Error inflating class com.visa.checkout.CheckoutButton
    Caused by: java.lang.ClassNotFoundException: com.visa.checkout.CheckoutButton
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at android.view.LayoutInflater.createView(LayoutInflater.java:815)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at pl.mobiltek.paymentsmobile.dotpay.fragment.UserDataFragment.onCreateView(UserDataFragment.java:146)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at pl.mobiltek.paymentsmobile.dotpay.activity.PaymentActivity.onStart(PaymentActivity.java:109)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7980)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3539)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2193)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7971)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.visa.checkout.CheckoutButton" on path: DexPathList[[zip file "/data/app/com.smartcode.myapplication-zc5YrFrjK_cRtUbF0lxesg==/base.apk"],nativeLibraryDirectories=[/data/app/com.smartcode.myapplication-zc5YrFrjK_cRtUbF0lxesg==/lib/arm64, /data/app/com.smartcode.myapplication-zc5YrFrjK_cRtUbF0lxesg==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 40 more`

**Comment by mekkolodziejski** [comment]
Trzeba skopiowac biblioteke do app/libs/visacheckout-android-sdk-6.6.1.aar
