### ISSUE TITLE
Crash when selecting "Karty płatnicze" when  loadLastSelectedChannel is set to false

### ISSUE THREAD

**Issue by Naitbit** [dotpay/Mobile-SDK-Android#5]
UserDataFragment crashes when it is configured to not load last channel:
```kotlin
AppSDK.initialize(app)
Configuration.loadLastSelectedChannel(false)
PaymentManager.getInstance().applicationVersion = Configuration.TEST_VERSION
```
This happens consistently on multiple devices (like Nexus 5 with Android 6, and Samsung Galaxy S3 with Android 4.4.4)

stacktrace:
```
FATAL EXCEPTION: main
Process: pl.******, PID: 26***
java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.********/pl.mobiltek.paymentsmobile.dotpay.activity.PaymentActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'pl.mobiltek.paymentsmobile.dotpay.model.PaymentMethod$PaymentMethodType pl.mobiltek.paymentsmobile.dotpay.model.PaymentMethod.getPaymentMethodType()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'pl.mobiltek.paymentsmobile.dotpay.model.PaymentMethod$PaymentMethodType pl.mobiltek.paymentsmobile.dotpay.model.PaymentMethod.getPaymentMethodType()' on a null object reference
    at pl.mobiltek.paymentsmobile.dotpay.view.ChannelFormView.setChannelForm(ChannelFormView.java:91)
    at pl.mobiltek.paymentsmobile.dotpay.fragment.UserDataFragment.initSelectedPaymentMethodLogo(UserDataFragment.java:287)
    at pl.mobiltek.paymentsmobile.dotpay.fragment.UserDataFragment.showAppropriateChannelView(UserDataFragment.java:266)
    at pl.mobiltek.paymentsmobile.dotpay.fragment.UserDataFragment.showAppropriateFormSection(UserDataFragment.java:237)
    at pl.mobiltek.paymentsmobile.dotpay.presenter.UserDataPresenter.loadForms(UserDataPresenter.java:41)
    at pl.mobiltek.paymentsmobile.dotpay.fragment.UserDataFragment.onCreateView(UserDataFragment.java:143)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
    at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
    at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
    at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
    at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
    at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
    at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
    at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3171)
    at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:192)
    at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:552)
    at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
    at pl.mobiltek.paymentsmobile.dotpay.activity.PaymentActivity.onStart(PaymentActivity.java:96)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
    at android.app.Activity.performStart(Activity.java:6268)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

This does not seem to happen when `Configuration.loadLastSelectedChannel` is set to `true` or when selecting other payment options.

**Comment by wpawel** [comment]
please check the [latest version 1.2.1-6](https://github.com/dotpay/Mobile-SDK-Android/tree/1.2.1-6)

**Comment by Naitbit** [comment]
Thanks
